# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tfgg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/ctc/led_lights/led_lights.cache/wt [current_project]
set_property parent.project_path E:/ctc/led_lights/led_lights.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/ctc/led_lights/xilinx.com_user_ctc8_1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet E:/ctc/led_lights/led_lights.runs/ctc8_0_synth_1/ctc8_0.dcp
set_property used_in_implementation false [get_files E:/ctc/led_lights/led_lights.runs/ctc8_0_synth_1/ctc8_0.dcp]
read_verilog -library xil_defaultlib {
  E:/ctc/led_lights/led_lights.srcs/sources_1/new/s_38.v
  E:/ctc/led_lights/led_lights.srcs/sources_1/new/clock_div.v
  E:/ctc/led_lights/led_lights.srcs/sources_1/new/led_lights.v
}
read_xdc E:/ctc/led_lights/led_lights.srcs/constrs_1/new/led_lights.xdc
set_property used_in_implementation false [get_files E:/ctc/led_lights/led_lights.srcs/constrs_1/new/led_lights.xdc]

synth_design -top led_lights -part xc7a100tfgg484-1
write_checkpoint -noxdef led_lights.dcp
catch { report_utilization -file led_lights_utilization_synth.rpt -pb led_lights_utilization_synth.pb }
