# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tfgg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/ctc/led_lights/led_lights.cache/wt [current_project]
set_property parent.project_path E:/ctc/led_lights/led_lights.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths e:/ctc/led_lights/xilinx.com_user_ctc8_1.0 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_ip e:/ctc/led_lights/led_lights.srcs/sources_1/ip/ctc8_0/ctc8_0.xci
set_property is_locked true [get_files e:/ctc/led_lights/led_lights.srcs/sources_1/ip/ctc8_0/ctc8_0.xci]

synth_design -top ctc8_0 -part xc7a100tfgg484-1 -mode out_of_context
rename_ref -prefix_all ctc8_0_
write_checkpoint -noxdef ctc8_0.dcp
catch { report_utilization -file ctc8_0_utilization_synth.rpt -pb ctc8_0_utilization_synth.pb }
if { [catch {
  file copy -force E:/ctc/led_lights/led_lights.runs/ctc8_0_synth_1/ctc8_0.dcp e:/ctc/led_lights/led_lights.srcs/sources_1/ip/ctc8_0/ctc8_0.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}
if { [catch {
  write_verilog -force -mode synth_stub e:/ctc/led_lights/led_lights.srcs/sources_1/ip/ctc8_0/ctc8_0_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode synth_stub e:/ctc/led_lights/led_lights.srcs/sources_1/ip/ctc8_0/ctc8_0_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}
if { [catch {
  write_verilog -force -mode funcsim e:/ctc/led_lights/led_lights.srcs/sources_1/ip/ctc8_0/ctc8_0_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}
if { [catch {
  write_vhdl -force -mode funcsim e:/ctc/led_lights/led_lights.srcs/sources_1/ip/ctc8_0/ctc8_0_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if {[file isdir E:/ctc/led_lights/led_lights.ip_user_files/ip/ctc8_0]} {
  catch { 
    file copy -force e:/ctc/led_lights/led_lights.srcs/sources_1/ip/ctc8_0/ctc8_0_stub.v E:/ctc/led_lights/led_lights.ip_user_files/ip/ctc8_0
  }
}

if {[file isdir E:/ctc/led_lights/led_lights.ip_user_files/ip/ctc8_0]} {
  catch { 
    file copy -force e:/ctc/led_lights/led_lights.srcs/sources_1/ip/ctc8_0/ctc8_0_stub.vhdl E:/ctc/led_lights/led_lights.ip_user_files/ip/ctc8_0
  }
}
